title: Bio-Coordination Chemistry
description: CHE5EJ303 – Course Website
theme: jekyll-theme-cayman

header_pages:
  - schedule.md
  - slides.md
  - assignments.md
  - resources.md
  - syllabus.md
  - quiz.md

collections:
  announcements:
    output: true
